# Generated by Django 3.1.4 on 2020-12-16 12:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201216_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='country_of',
            field=django_countries.fields.CountryField(default=True, max_length=2),
            preserve_default=False,
        ),
    ]
