# Generated by Django 3.1.4 on 2020-12-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_country_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
